version: '3'

services:
  # MySQL
  
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_TCP_PORT: "${DATABASE_PORT}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_DB}"
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    # volumes:
    #   - mysql_data:/var/lib/mysql
    #   - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
    #   - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - db
  mongo:
    image: mongo
    restart: always
    networks:
      - db
  api:
    build:
      dockerfile: Dockerfile
      context: ./transaction
    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_DATABASE_HOST: mongo
      MONGO_DATABASE_PORT: 27017
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    depends_on:
      - mysql
    ports:
      - "81:3000"
    networks:
      - db
      - socket
  app:
    build:
      dockerfile: Dockerfile
      context: ./my-app
    restart: always
    environment:
      REACT_APP_SERVER: "http://localhost:81"
    depends_on:
      - api
    networks:
      - socket
    ports:
      - "80:3000"
networks:
  db: 
    driver: bridge
    name: db
  socket:
    driver: bridge
    name: socket
# volumes:
#   mysql_data:
#     name: mysql_data


